### ISSUE TITLE
VU Server crashes when other usb port is used

### ISSUE THREAD

**Issue by HompieDompie** [SasaKaranovic/VU-Server#28]
On a windows 11 pc the VU Server process crashes on startup when another usb port already has been opened. 
(In my case a zigbee stick on COM3). After removing the stick the VU server starts and works ok. The VU meters are connected to COM4.

Errors in logging:

```
2024-02-21 12:26:30,020 INFO __init__(545) VU1 HUB port: COM3 - USB Serial Port (COM3)
2024-02-21 12:26:30,022 ERROR main(657) VU Dials API service crashed during setup.
Traceback (most recent call last):
  File "server.py", line 655, in main
  File "server.py", line 546, in __init__
  File "dial_driver.py", line 20, in __init__
  File "serial_driver.py", line 36, in __init__
  File "serial\serialwin32.py", line 33, in __init__
  File "serial\serialutil.py", line 244, in __init__
  File "serial\serialwin32.py", line 64, in open
serial.serialutil.SerialException: could not open port 'COM3': PermissionError(13, 'Toegang geweigerd.', None, 5)
```

**Comment by SasaKaranovic** [comment]
You can try manually specifying COM port you want to be used for VU dials.

In you VU Server installation directory, there should be `_internal` folder that contains `config.yaml`
You can open it with any text editor and add COM4. Your config file should look something like this 

```yaml
server:
  hostname: localhost
  port: 5340
  communication_timeout: 10
  dial_update_period: 200
  master_key: cTpAWYuRpA2zx75Yh961Cg

hardware:
  port: COM4

```

**Comment by HompieDompie** [comment]
That does indeed work around the problem, the server process now starts ok.
Thanks.
