### ISSUE TITLE
Fetching the list of dials very quickly causes race condition and exception

### ISSUE THREAD

**Issue by sqozz** [SasaKaranovic/VU-Server#31]
While implementing python bindings for the server API, I realized that calling `/api/v0/dial/list` in rapid succession causes the server to throw an exception:

```python
Exception in callback <bound method ServerDialHandler.periodic_dial_update of <server_dial_handler.ServerDialHandler object at 0x7fb2c8adfdd0>>
Traceback (most recent call last):
  File "/home/sqozz/git/VU-Server/venv/lib/python3.11/site-packages/tornado/ioloop.py", line 937, in _run
    val = self.callback()
          ^^^^^^^^^^^^^^^
  File "/home/sqozz/git/VU-Server/server_dial_handler.py", line 46, in periodic_dial_update
    ret = self._periodic_update_dial_backlight()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sqozz/git/VU-Server/server_dial_handler.py", line 133, in _periodic_update_dial_backlight
    dial['backlight']['white']
    ~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'white'
```

I think this might be a race-condition between the data flowing into the server from the "list"-command and a periodic update running simultaneously maybe?

I quickly hacked out all references to "white" and it works now. This is very dirty and most likely not correct so I'm just attaching it here for reference but won't create a PR.

```diff
diff --git a/dial_driver.py b/dial_driver.py
index 6c080da..90f3455 100644
--- a/dial_driver.py
+++ b/dial_driver.py
@@ -478,14 +478,14 @@ class DialSerialDriver(SerialHardware):
         logger.debug(f"@dial_display_show(device={device})")
         return self._sendCommand(self.commands.COMM_CMD_DISPLAY_SHOW_IMG, self.data_type.COMM_DATA_SINGLE_VALUE, 1, int(device))

-    def dial_set_backlight(self, device, red, green, blue, white):
-        logger.debug(f"@dial_set_backlight(device={device}, red={red}, green={green}, green={green}, blue={blue}, white={white})")
+    def dial_set_backlight(self, device, red, green, blue):
+        logger.debug(f"@dial_set_backlight(device={device}, red={red}, green={green}, green={green}, blue={blue})")
         device = self._verify_device(device)
         self.dials[device]['rgbw'][0] = red
         self.dials[device]['rgbw'][1] = green
         self.dials[device]['rgbw'][2] = blue
-        self.dials[device]['rgbw'][3] = white
-        data = [device, red, green, blue, white]
+        self.dials[device]['rgbw'][3] = 0
+        data = [device, red, green, blue, 0]
         return self._sendCommand(self.commands.COMM_CMD_SET_RGB_BACKLIGHT, self.data_type.COMM_DATA_MULTIPLE_VALUE, len(data), data)

     def dial_send_keep_comm_alive(self, device):
diff --git a/server.py b/server.py
index 7a940fe..98d9c93 100644
--- a/server.py
+++ b/server.py
@@ -143,7 +143,7 @@ class Device_Backlight_Handler(BaseHandler):
         if not self.is_valid_api_key():
             return self.send_response(status='fail', message='Unauthorized', status_code=401)

-        if self.handler.dial_set_backlight(dial_uid=dial_uid, red=red, green=green, blue=blue, white=white):
+        if self.handler.dial_set_backlight(dial_uid=dial_uid, red=red, green=green, blue=blue):
             return self.send_response(status='ok', message='Update queued', status_code=201)
         return self.send_response(status='fail', message='Invalid dial_uid or device is offline.', status_code=503)

@@ -597,7 +597,7 @@ class Dial_API_Service(Application):
             for dial in self.dial_driver.dials:
                 logger.debug(f"Shutting down dial {dial}")
                 self.dial_driver.set_dial(dialID=dial, value=0)
-                self.dial_driver.dial_set_backlight(device=dial, red=0, green=0, blue=0, white=0)
+                self.dial_driver.dial_set_backlight(device=dial, red=0, green=0, blue=0)

         except Exception as e:
             logger.error("Failed to gracefully shut down dials")
diff --git a/server_dial_handler.py b/server_dial_handler.py
index 3cbf352..147c475 100644
--- a/server_dial_handler.py
+++ b/server_dial_handler.py
@@ -80,7 +80,7 @@ class ServerDialHandler:
         # and also so that we can uniquely identify each dial.
         for dial in dials:
             dial['value'] = 0
-            dial['backlight'] = {'red':0, 'green':0, 'blue':0, 'white':0 }
+            dial['backlight'] = {'red':0, 'green':0, 'blue':0}
             dial['image_file'] = self._check_upload_for_dial_image(dial['uid'])
             dial['update_deadline'] = time()
             dial['value_changed'] = False
@@ -129,8 +129,7 @@ class ServerDialHandler:
                 self.dial_driver.dial_set_backlight(dial['index'],
                                                     dial['backlight']['red'],
                                                     dial['backlight']['green'],
-                                                    dial['backlight']['blue'],
-                                                    dial['backlight']['white']
+                                                    dial['backlight']['blue']
                                                     )
                 dial['backlight_changed'] = False
                 dial['update_deadline'] = time() + self.communication_timeout
@@ -243,7 +242,7 @@ class ServerDialHandler:

         return True

-    def dial_set_backlight(self, dial_uid, red, green, blue, white):
+    def dial_set_backlight(self, dial_uid, red, green, blue):
         if not self._dial_exists(dial_uid):
             logger.error(f"Dial {dial_uid} does not exist in dial list.")
             return False
@@ -251,23 +250,21 @@ class ServerDialHandler:
         red = self._convert_to_int(red)
         green = self._convert_to_int(green)
         blue = self._convert_to_int(blue)
-        white = self._convert_to_int(white)

         red = min(red, 100)
         green = min(green, 100)
         blue = min(blue, 100)
         blue = min(blue, 100)
-        white = min(white, 100)

-        new_value = {'red':red, 'green':green, 'blue':blue, 'white':white }
+        new_value = {'red':red, 'green':green, 'blue':blue}

         # Check if already at value
         if self.dials[dial_uid]['backlight'] == new_value:
-            logger.debug(f"Dial {dial_uid} already at {red}:{green}:{blue}:{white}")
+            logger.debug(f"Dial {dial_uid} already at {red}:{green}:{blue}")
             return True

-        logger.debug(f"Queueing dial {dial_uid} RGBW update to {red}:{green}:{blue}:{white}")
-        self.dials[dial_uid]['backlight'] = {'red':red, 'green':green, 'blue':blue, 'white':white }
+        logger.debug(f"Queueing dial {dial_uid} RGBW update to {red}:{green}:{blue}")
+        self.dials[dial_uid]['backlight'] = {'red':red, 'green':green, 'blue':blue }
         self.dials[dial_uid]['backlight_changed'] = True
         return True
```

**Comment by SasaKaranovic** [comment]
Hi @sqozz 
Thank you for reporting this. I am not sure why there would be a `KeyError: 'white'` issue only when you try to access the server in rapid succession but not when you access it normally.

But I think regardless of that, the periodic callback function should really be changed to `async` method so it does not block the server from handling incoming requests while it's updating the dials. I will create a separate issue for that.

Out of curiosity, can you please provide some additional information on how are you testing the server and perhaps also what are you making? :)

**Comment by sqozz** [comment]
I'm building python-bindings for the API. I implemented it so that every time you access the "dials"-object (a list of all available dials) it makes a request to the `/api/v0/dial/list`-endpoint. So I had the following code to test my bindings:

```python
dial = dials[dials.index("my_dial_uuid")]
dial.value = 50
dial.color = vu1.Color(100, 0, 0)
```

accessing the attributes like `value` or `color` causes my code to request the dial-status via the `/api/v0/dial/UUID/status`-endpoint. So I think what happens here is that the server is confused by the responses because the backlight-dict on a `list`-call does not contain "white" while the answer from `status` does have it.

BTW: I was able to reproduce this bug also by a simple while-loop in bash:

```bash
while true; do curl "localhost:5340/api/v0/dial/list?key=my_api_key"; done
```

**Comment by SasaKaranovic** [comment]
Thanks @sqozz 
I will look into this. Right now I am unable to replicate this test through Postman or sequential API calls.

BTW please note that dial list will not change often, in most cases it will "never" change. So calling an API every time user wants to get a list of dials is very wasteful and I would strongly advise against that. Instead you should call the API server to retrieve the dial list and then cache it. Any subsequent request should get the cached list instead of making a new call to the API server.
